language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/SoftwareSerialExample
    - PLATFORMIO_CI_SRC=examples/TwoPortReceive

install:
    - pip install -U platformio
    - pio uprade
    - pio update

script:
    - platformio ci --lib="." --board=mayfly
